### ISSUE TITLE
Changing properties from Klak

### ISSUE THREAD

**Issue by Latentnaut** [keijiro/CosineGradient#1]
Would be nice to have access to the properties (opacity, direction, frequency, etc) from Klak.

<img width="478" alt="screen shot 2017-03-13 at 12 24 07" src="https://cloud.githubusercontent.com/assets/22867200/23852482/4edbc618-07e8-11e7-8b7c-2ad031070918.png">

**Comment by keijiro** [comment]
Sorry but it's just an example of usage of CosineGradient. It's out of the scope of this repository.

**Comment by keijiro** [comment]
Reopened for some reason. Please don't expect too much... I just thought that it should be memorized.
